### PR TITLE
Created CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by jaidh01**
I have created the code_of_conduct.md.

fixes. #7.

### CODE REVIEW

**Comment by jaidh01** [comment]
hi @Akasxh, 
I request you to please add the `gssoc-extd, hacktoberfest and level 1` label to this issue before merging. As, without that it is not going to counted in my gssoc-extd.

Thank you for your time.

**Comment by jaidh01** [comment]
Hi @Akasxh, I just saw that you have removed the `level 1` label.
I request you to please add it back, as without that it is not getting count in my gssoc-extd.

**Comment by AKSHITHA-CHILUKA** [comment]
@Akasxh despite of many times telling you have not changed the labels.
The crt labels are level3 with no spaces , gssoc-ext is the label not gssoc24-extd , hactoberfest-accepted is the label not hactoberfest .
I hope you will change all the label's in all the issues and pr's as soon as possible .

**Comment by jaidh01** [comment]
Hi @Akasxh, I just saw that you have removed the `level 1` label.
I request you to please add it back, as without that it is not getting count in my gssoc-extd.

Thank you for your time!

**Pull request merged**
