### PR TITLE
Models for Terrain Recognization under Transfer Learning

### PR DESCRIPTION
**Pull request by Shreyansh-G**
i had add two notebook consist of model MobileNetV2(9.71 mb) acheiving accuracy of 91 % and ConvNext_Tiny which achieves accuracy of 92% approximately and also added my mobilnet model in transfer model section.

### CODE REVIEW

**Comment by Akasxh** [comment]
can you show screenshots of your accuracy vs training progression for me to see how it progressed?

Also add a seperate readme file like the one in main, inside the folder of transfer learning supporting that it is the core technique used with model weight average inference speed all insede one folder.

till then ill review your pr.

**Comment by Shreyansh-G** [comment]
it is in both notebook and i will add readme of model architecture i used in both with description or I will add my details in readme section already exist.

**Comment by Shreyansh-G** [comment]
imagegit

**Comment by Akasxh** [comment]
Yes , I just viewed the ipynb file, the work looks good. Add/change the existing readme and add why your model isi outperforming the prev transfer learning model. Also add these screenshots and model weight details from ipynb file to thhe readme to make it more detailed. 

The previous readme was just subpar in terms of showing how the architecture is and in explaining, seeing that your model is outperforming, make a quality readme as well!

**Comment by Shreyansh-G** [comment]
image

**Comment by Shreyansh-G** [comment]
Thanks for compliment i will try my best to write best readme with visuals.

**Comment by Akasxh** [comment]
Also inside transfer learning folder the only ipynb file should be your code as yours is currently best performing, just add other files into a new folder inside called past architecture and add the rest files there.

**Comment by Shreyansh-G** [comment]
i had done everything as you suggested.

**Comment by Akasxh** [comment]
could you further add all the images inside a new image folder in transfer learning so as everything is organised

**Comment by Akasxh** [comment]
everything else is fine

**Comment by Shreyansh-G** [comment]
done it!

**Comment by Shreyansh-G** [comment]
Please merge it before 30-10-2024

**Comment by Akasxh** [comment]
done!

**Pull request merged**
